#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

typeset -U path

path=(
  $HOME/bin
  $HOME/.cargo/bin
  $HOME/.yarn/bin
  $HOME/.bundle/bin
  $path
)

local texliveversion="2019"
export PATH="/usr/local/texlive/${texliveversion}/bin/x86_64-linux:$PATH"
export MANPATH="/usr/local/texlive/${texliveversion}/texmf/doc/man:$MANPATH"
export INFOPATH="/usr/local/texlive/${texliveversion}/texmf/doc/info:$INFOPATH"

export GEM_HOME="$HOME/.gem/ruby"
export BUNDLE_PATH="$HOME/.bundle"

export LESS='-F -g -i -M -R -S -X -z-4'
export LESSHISTFILE='-' # do not create ~/.lesshst

if command -v vimx &>/dev/null; then
  export VISUAL='vimx'
elif command -v vim &>/dev/null; then
  export VISUAL='vim'
else
  export VISUAL='vi'
fi
export EDITOR=$VISUAL
[[ $TMUX != "" ]] && export TERM='tmux-256color'

alias ssu='sleep 3600 && dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.Suspend boolean:true'
alias v="$VISUAL"
alias utop='utop -require batteries -require ppx_deriving.std -require cil'
alias octave-cli='octave-cli -q'
alias mbs='/usr/bin/rsync -av --delete --delete-excluded --exclude "/.cache/" --exclude "/Downloads/MediathekView/" /home/stefan/ /run/media/stefan/backup/stefan/ && sync'
alias killpass='pkill -f "/usr/bin/mono --verify-all /usr/lib/keepass/KeePass.exe"'
alias dotfilesgit="/usr/bin/git --git-dir=$HOME/.dotfilesgit/ --work-tree=$HOME"
alias dfg=dotfilesgit
alias gdb='gdb -q'
unalias o

function o() {
  nohup xdg-open "$*" > /dev/null 2>&1 &
}

. ~/.zplugins/calc.plugin.zsh/calc.plugin.zsh

function peek() { tmux split-window -p 33 "$EDITOR" "$@" || exit; }

# Solarized dircolors from https://github.com/seebi/dircolors-solarized
eval `dircolors ~/.dircolors.256dark`

# OPAM configuration
#. ~/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

function dfg-update() {
  dfg pull --rebase --autostash
  git -C ~/.zprezto pull --rebase --autostash
  git -C ~/.zprezto submodule update --init --recursive
  git -C ~/.zplugins/calc.plugin.zsh pull --rebase --autostash
}

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi
