#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

typeset -U path

path=(
  $HOME/.local/bin
  $HOME/.cargo/bin
  $path
)

local texliveversion=$(cd /usr/local/texlive &>/dev/null && print -C1 -O [0-9][0-9][0-9][0-9] | head -n 1)
if [[ -n $texliveversion ]]
then
  export PATH="/usr/local/texlive/${texliveversion}/bin/x86_64-linux:$PATH"
  export MANPATH="/usr/local/texlive/${texliveversion}/texmf/doc/man:$MANPATH"
  export INFOPATH="/usr/local/texlive/${texliveversion}/texmf/doc/info:$INFOPATH"
fi

export LESS='-F -g -i -M -R -S -X -z-4'
export LESSHISTFILE='-' # do not create ~/.lesshst

if command -v vimx &>/dev/null; then
  export VISUAL='vimx'
elif command -v vim &>/dev/null; then
  export VISUAL='vim'
else
  export VISUAL='vi'
fi
export EDITOR=$VISUAL
[[ $TMUX != "" ]] && export TERM='tmux-256color'

alias git='noglob git'
alias v="$VISUAL"
alias octave-cli='octave-cli -q'
alias dfg="/usr/bin/git --git-dir=$HOME/.dotfilesgit/ --work-tree=$HOME"
alias gdb='gdb -q'
alias m='systemctl --user start offlineimap.service && mutt'

function __my_calc {
  noglob octave-cli --eval "$*"
}
aliases[=]='noglob __my_calc'

unalias o
function o() {
  nohup xdg-open "$*" > /dev/null 2>&1 &
}

function fixssh() {
  if [[ -n $TMUX ]]
  then
    eval $(tmux show-environment -s DISPLAY)
    eval $(tmux show-environment -s SSH_AUTH_SOCK)
    eval $(tmux show-environment -s SSH_CONNECTION)
  fi
}

# Solarized dircolors from https://github.com/seebi/dircolors-solarized
eval `dircolors ~/.dircolors.256dark`

function dfg-update() {
  dfg pull --rebase --autostash
  git -C ~/.zprezto pull --rebase --autostash
  git -C ~/.zprezto submodule update --init --recursive
  git -C ~/.zplugins/calc.plugin.zsh pull --rebase --autostash
}

# Disable Ctrl+S and Ctrl+Q bindings
stty stop undef
stty start undef
stty -ixon
stty -ixoff

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi
